Added starter theme
lemberg/draft-theme pull request #16
Opened 2017-07-24 08:54 UTC by bogdan-hepting

Added STARTER theme

- Moved all theme preprocess functions to `includes` directory
- Added `gulpfile.js` and `watchers`
- Added linting for

1. scss files - `.scss-lint.yml`

1.

2017-07-24 16:37 UTC, T2L requested changes
As you have added SCSS and JS lint, please update Travis - it should run those checks!

2017-07-24 16:37 UTC, T2L commented on STARTER/scss/style.scss
> +p {
I think we nee to make it just an empty file

2017-07-24 16:37 UTC, T2L commented on STARTER/package.json
> +  "license": "ISC",
what's an `ISC`?

2017-07-24 16:37 UTC, T2L commented on STARTER/package.json
> +  "name": "starter",
Probably should be `STARTER`

2017-07-24 16:37 UTC, T2L commented on STARTER/js/src/theme.js
> +/**
I don't think we need this demo JS code here. Just a template JS file would be enough

2017-07-24 16:37 UTC, T2L commented on STARTER/includes/node.inc
> +/**
We do not assume any bundles exist. Please remove

2017-07-24 16:37 UTC, T2L commented on STARTER/STARTER.theme
> +
Extra space

2017-07-24 16:37 UTC, T2L commented on STARTER/STARTER.libraries.yml
> +    js/dist/themekit.js: {}
I don't like `themekit` here, maybe `draft`. Also, needs to be changed in gulpfile

2017-07-24 16:37 UTC, T2L commented on STARTER/STARTER.info.yml
> +  - css/dist/wysiwyg.css
We need to create corresponding scss file, no?

2017-07-24 16:37 UTC, T2L commented on STARTER/.scss-lint.yml
> +  final-newline: 1
Missing empty line

2017-07-24 16:37 UTC, T2L commented on STARTER/.gitignore
> +# Node modules #
This file contains a lot of stuff. I think it should be project specific, not user machine specific.

2017-07-25 08:21 UTC, bogdan-hepting commented
@T2L I've fixed all mistakes, you noticed

2017-10-16 14:30 UTC, andrew-147 approved these changes

2017-10-16 14:42 UTC, andrew-147 commented
@T2L Added newline at the end of files.

2017-10-16 14:46 UTC, T2L approved these changes

2017-10-16 14:46 UTC, merged