Add helper functions to get inline css style for bg image in STARTER
lemberg/draft-theme pull request #31
Opened 2017-10-23 15:31 UTC by andrew-147

2017-10-24 10:16 UTC, T2L requested changes

2017-10-24 10:16 UTC, T2L commented on STARTER/STARTER.theme
>  <?php
Move this to draft_theme.theme, as our theme will be a subtheme - so parent code will be available

2017-10-24 10:16 UTC, T2L commented on STARTER/STARTER.theme
> + * STARTER Drupal 8 theme based on Draft theme.
Fix comment as this will go in draft

2017-10-24 10:16 UTC, T2L commented on STARTER/STARTER.theme
> + * @param mixed $entity
Replace `mixed` with `Drupal\Core\Entity\ContentEntityInterface`

2017-10-24 10:16 UTC, T2L commented on STARTER/STARTER.theme
> +function _get_entity_image_inline_style($entity, $field_name, $image_style) {
Prefix with `draft_` and add $field_image_name (defaults to 'field_image')

2017-10-24 10:16 UTC, T2L commented on STARTER/STARTER.theme
> +  $rendered_style = '';
rename to `$output`

2017-10-24 10:16 UTC, T2L commented on STARTER/STARTER.theme
> +  if (!$entity->$field_name->isEmpty()) {
We might want to raise `InvalidArgumentException` when no field found. Let's think about it

2017-10-24 10:16 UTC, T2L commented on STARTER/STARTER.theme
> +      $rendered_style = 'style="background-image: url(' . $url . ');"';
Return plain url, constructing style attribute is template responsibility

2017-10-24 10:16 UTC, T2L commented on STARTER/STARTER.theme
> + * @param \Drupal\file\Entity\File $file
Replace with `Drupal\file\FileInterface`

2017-10-24 10:16 UTC, T2L commented on STARTER/STARTER.theme
> +    $url = ImageStyle::load($image_style)->buildUrl($uri);
No check for existing image style, raise `InvalidArgumentException`

2017-10-24 10:16 UTC, T2L commented on STARTER/STARTER.theme
> +function _get_image_style_url(File $file, $image_style) {
$image_style should be optional, i.e. `$image_style = NULL`

2017-10-24 16:24 UTC, andrew-147 commented on STARTER/STARTER.theme
>  <?php
Done.

2017-10-24 16:24 UTC, andrew-147 commented on STARTER/STARTER.theme
> + * STARTER Drupal 8 theme based on Draft theme.
Done.

2017-10-24 16:24 UTC, andrew-147 commented on STARTER/STARTER.theme
> + * @param mixed $entity
Done.

2017-10-24 16:24 UTC, andrew-147 commented on STARTER/STARTER.theme
> +function _get_entity_image_inline_style($entity, $field_name, $image_style) {
Done.

2017-10-24 16:24 UTC, andrew-147 commented on STARTER/STARTER.theme
> +  $rendered_style = '';
Done.

2017-10-24 16:25 UTC, andrew-147 commented on STARTER/STARTER.theme
> +      $rendered_style = 'style="background-image: url(' . $url . ');"';
Done.

2017-10-24 16:25 UTC, andrew-147 commented on STARTER/STARTER.theme
> + * @param \Drupal\file\Entity\File $file
Done.

2017-11-02 20:29 UTC, T2L approved these changes

2017-11-02 20:29 UTC, merged